name: Terraform GitHub Actions

on: 
  push:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:  
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: latest

    - name: Terraform init
      id: init
      run: terraform init

    - name: Terraform format
      id: fmt
      run: terraform fmt

    - name: Terraform validate
      id: validate
      run: terraform validate

    - name: Terraform plan
      id: plan
      run: terraform plan

  Deploy:
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
    
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:  
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: latest

    - name: Terraform init
      id: init
      run: terraform init
    
    - name: Terraform apply
      id: apply
      run: terraform apply -auto-approve